//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPToDoList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskState
    {
        public TaskState()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public string ALPHAID { get; set; }
        public string TITLE { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
